### ISSUE TITLE
branch discussion

### ISSUE THREAD

**Issue by HowDoIUseGit** [SE-TINF22B6/CookPit#5]
## manage branches
# To-do list, if necessary:
1. [x] create a new branch for each head topic (frontend, backend, ...)
2. [x] block easy main push/merge rights
3. [x] discuss develop style --> does every new feature require a new subbranch?
