### ISSUE TITLE
Create basic Landing page

### ISSUE THREAD

**Issue by mirak55** [SE-TINF22B6/CookPit#7]
## Specification
# To-do list, if necessary:
1. [ ] Create entry page
2. [ ] Create navigation bar
3. [ ] Implement basic features
